const CHOICE_PLACEHOLDER_COMPONENTS = new Set([
  'select',
  'dictselect',
  'radio',
  'radiobutton',
  'checkbox',
  'cascader',
  'treeselect',
  'customselect',
  'dateselect',
  'datepicker',
  'timepicker',
  'time',
  'date',
  'datetime',
  'daterange',
  'datetimerange',
  'timerange',
  'upload',
  'fileupload',
  'imageupload',
  'userselect',
  'userpicker',
  'sysuserselect',
  'forgeuserselect',
  'orgtreeselect',
  'orgselect',
  'organizationselect',
  'departmentselect',
  'departmenttreeselect',
  'deptselect',
  'depttreeselect',
  'forgeorgtreeselect',
  'regiontreeselect',
  'transfer',
])

const COMPONENT_DEFAULT_LABELS = {
  input: '输入框',
  textarea: '多行文本',
  number: '数字',
  money: '金额',
  slider: '滑块',
  rate: '评分',
  color: '颜色选择',
  select: '静态下拉',
  dictSelect: '字典下拉',
  radio: '单选',
  radioButton: '按钮单选',
  checkbox: '多选',
  transfer: '穿梭框',
  cascader: '级联选择',
  treeSelect: '树形选择',
  customSelect: '远程选择',
  date: '日期',
  datetime: '日期时间',
  time: '时间',
  daterange: '日期范围',
  datetimerange: '日期时间范围',
  timerange: '时间范围',
  fileUpload: '文件上传',
  imageUpload: '图片上传',
  userSelect: '人员选择',
  orgTreeSelect: '组织选择',
  regionTreeSelect: '区域选择',
}

export function isChoicePlaceholderComponent(componentKey = '') {
  return CHOICE_PLACEHOLDER_COMPONENTS.has(String(componentKey || '').toLowerCase())
}

export function buildDefaultPlaceholder(componentKey = '', label = '') {
  const cleanLabel = String(label || '').trim()
  const prefix = isChoicePlaceholderComponent(componentKey) ? '请选择' : '请填写'
  return cleanLabel ? `${prefix}${cleanLabel}` : prefix
}

export function shouldSyncPlaceholder(component = {}) {
  const currentPlaceholder = component.props?.placeholder
  if (currentPlaceholder === undefined || currentPlaceholder === null)
    return true
  const currentText = String(currentPlaceholder).trim()
  if (!currentText)
    return true
  return isAutoGeneratedPlaceholder(component, currentText)
}

export function buildFieldAssetPlaceholderPatch(component = {}, payload = {}) {
  const hasPlaceholder = Object.prototype.hasOwnProperty.call(payload, 'placeholder')
  const incomingPlaceholder = hasPlaceholder ? String(payload.placeholder || '') : ''
  const currentPlaceholder = String(component.props?.placeholder || '')
  if (hasPlaceholder && incomingPlaceholder !== currentPlaceholder)
    return { placeholder: incomingPlaceholder }
  if (Object.prototype.hasOwnProperty.call(payload, 'fieldName') && shouldSyncPlaceholder(component)) {
    return {
      placeholder: buildDefaultPlaceholder(component.componentKey, payload.fieldName),
    }
  }
  return hasPlaceholder ? { placeholder: incomingPlaceholder } : {}
}

function isAutoGeneratedPlaceholder(component = {}, placeholder = '') {
  const text = String(placeholder || '').trim()
  if (!text)
    return true
  return resolveAutoPlaceholderLabels(component)
    .some(label => buildAutoPlaceholderCandidates(component.componentKey, label).includes(text))
}

function buildAutoPlaceholderCandidates(componentKey = '', label = '') {
  const cleanLabel = String(label || '').trim()
  const prefixes = isChoicePlaceholderComponent(componentKey)
    ? ['请选择']
    : ['请填写', '请输入', '请填入']
  return prefixes.map(prefix => cleanLabel ? `${prefix}${cleanLabel}` : prefix)
}

function resolveAutoPlaceholderLabels(component = {}) {
  const labels = [
    component.label,
    component.props?.label,
    component.props?.title,
    component.props?.header,
    component.fieldBinding?.fieldName,
    component.fieldBinding?.fieldCode,
    component.field,
    component.name,
    COMPONENT_DEFAULT_LABELS[component.componentKey],
    '字段',
  ]
  return Array.from(new Set(labels.map(label => String(label || '').trim()).filter(Boolean)))
}
